apm-server.frontend.enabled: true
apm-server.host: "0.0.0.0:8200"

output.elasticsearch:
  hosts: ["es01:9200", "es02:9200", "es03:9200"]
  protocol: "http"
  username: elastic
  # Read PW from apm-server.keystore
  password: "${ELASTIC_PASSWORD}"
  ssl.certificate_authorities: ["/usr/share/apm-server/certs/ca/ca.crt"]

setup.kibana:
  host: "http://kibana:5601"
  username: elastic
  password: "${ELASTIC_PASSWORD}"
  protocol: "http"
  ssl.enabled: false
  ssl.certificate_authorities: ["/usr/share/apm-server/certs/ca/ca.crt"]
